const StateList = [
  { id: 1, name: "alabama" },
  { id: 2, name: "alaska" },
  { id: 3, name: "arizona" },
  { id: 4, name: "arkansas" },
  { id: 5, name: "california" },
  { id: 6, name: "colorado" },
  { id: 7, name: "connecticut" },
  { id: 8, name: "delaware" },
  { id: 9, name: "district of columbia" },
  { id: 10, name: "florida" },
  { id: 11, name: "georgia" },
  { id: 12, name: "hawaii" },
  { id: 13, name: "idaho" },
  { id: 14, name: "illinois" },
  { id: 15, name: "indiana" },
  { id: 16, name: "iowa" },
  { id: 17, name: "kansas" },
  { id: 18, name: "kentucky" },
  { id: 19, name: "lousiana" },
  { id: 20, name: "maine" },
  { id: 21, name: "maryland" },
  { id: 22, name: "massachusetts" },
  { id: 23, name: "michigan" },
  { id: 24, name: "minnesota" },
  { id: 25, name: "mississippi" },
  { id: 26, name: "missouri" },
  { id: 27, name: "montana" },
  { id: 28, name: "nebraska" },
  { id: 29, name: "nevada" },
  { id: 30, name: "new hampshire" },
  { id: 31, name: "new jersey" },
  { id: 32, name: "new mexico" },
  { id: 34, name: "new york" },
  { id: 35, name: "north carolina" },
  { id: 36, name: "north dakota" },
  { id: 37, name: "ohio" },
  { id: 38, name: "oklahoma" },
  { id: 39, name: "oregon" },
  { id: 40, name: "pennsylvania" },
  { id: 41, name: "rhode island" },
  { id: 42, name: "south carolina" },
  { id: 43, name: "south dakota" },
  { id: 44, name: "tennessee" },
  { id: 45, name: "texas" },
  { id: 46, name: "utah" },
  { id: 47, name: "vermont" },
  { id: 48, name: "virginia" },
  { id: 49, name: "washington" },
  { id: 50, name: "west virginia" },
  { id: 51, name: "wisconsin" },
  { id: 52, name: "wyoming" },
];

export default StateList;
